server:
  servlet:
    session:
      cookie:
        secure: false

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:agenda}
    username: ${POSTGRES_USER:agenda}
    password: ${POSTGRES_PASSWORD:change-me}
  flyway:
    locations: classpath:db/migration,classpath:db/dev-seed
  mail:
    host: localhost
    port: ${MAILPIT_SMTP_PORT:1025}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

logging:
  level:
    br.com.agendaplatform: DEBUG
